export default {
  login: 'login',
  forgot_pwd: 'reset-pwd-mail',
  browse_skills: 'browseskill',
  dashboard: 'dashboard',
  badge_count: 'tabs/notifications/count',
  my_profile: 'my-profile',
  staffs: 'staffs',
  change_pwd: 'change-pwd',
  skill_requests: 'skill-requests',
  staff_list: 'staffs?isPaginate=false',
  approver_staffs: 'approver-staffs',
  requested_skills: 'requested-skills',
  completed_skills: 'completed-skills',
  skill_requests: 'skill-requests',
  skill_approval_finally: 'skill-approval',
  competencies_detail: 'competencies-detail',
  competency_assessment_request: 'competency-assessment-request',
  skill_approval: 'skill-approval?type=true',
  ongoing_skills: 'ongoing',
  skills: 'skills',
  notification: 'notification',
  refreshToken: 'auth/refresh-token/',
  getExtraConstant: 'constant-data/extra-constants/',
  getPensionAccounts: 'employee/pension-accounts',
  getPensionProviders: 'employee/pension-providers',
  createPrivatePensionAccount: 'employee/pension-accounts/private/create',
  updateDobandGender: 'employee/account-settings/dob-gender/',
  createStatePensionAccount: 'employee/pension-accounts/state-pension/create',
  getStatePensionOtherDetail: 'employee/pension-accounts/state-pension/other',
  getPrivatePensionDetail: 'employee/pension-accounts/private-pension/',
  getEmployerLinkPensionDetail:
    'employee/pension-accounts/employer-link-pension/',
  getStatePensionDetail: 'employee/pension-accounts/state-pension/',
  getUserDetail: 'employee/account-settings/',
  editUserDetail: 'employee/account-settings/update/',
  changePassword: 'employee/account-settings/update/password/',
  addAddress: 'employee/account-settings/address/',
  deleteAddress: 'employee/account-settings/address/',
  editAddress: 'employee/account-settings/address/',
  statePensionAgeCalculator: 'employee/calculate-state-pension',
  calculateLifeExpectancy: 'employee/calculate-life-expectancy',
  getSnapshots: 'employee/knowledgehub-video',
  videoWatched: 'employee/complate-video/',
  getSubscription: 'employee/packages',
  getContributionRate: 'employee/contribution-rates',
  smartprogram: 'employee/smartprogram/',
  savingRateCalculator: 'employee/saving-rate-calculator',
  savingRateTaxCalculator: 'employee/saving-rate-tax-calculator',
  getPensionValuation: 'employee/pension-accounts/valuation/',
  addValuationDB: 'employee/valuation/defined-benefit/create/',
  addValuationDC: 'employee/valuation/defined-contribution/create/',
  deleteValuationDC: 'employee/valuation/defined-contribution/',
  deleteValuationDB: 'employee/valuation/defined-benefit/',
  archiveAccount: 'employee/pension-accounts/archive/',
  unarchiveAccount: 'employee/pension-accounts/unarchive/',
  leaveScheme: 'employee/pension-accounts/',
  editPrivatePensionAccount: 'employee/pension-accounts/private/update/',
  editEmployeeLinkPension: 'employee/pension-accounts/',
  updateSavingRate: 'employee/contribution/change-request',
  cancelSavingRateRequest: 'employee/contribution/change-request/',
  getEmployeeContributionDetail: 'employee/',
  optInOutSalaryExchange: 'employee/change-request-opt-in-out',
  changeSmartProgrammeSetting: 'employee/smartprogram/',
  editStatePension: 'employee/pension-accounts/state-pension/',
  getDashboard: 'employee/dashboard',
  getYodleeToken: 'yodlee/user/token?loginName=',
  getTransactions: 'employee/pension-accounts/transactions/',
  updatePensionAccount: 'yodlee/pension-account/update/',
  emailToMaji: 'employee/email-to-maji',
  forgotPassword: 'auth/forget-password/employee',
  getArchivedAccounts: 'employee/archived/pension-accounts',
  getFinancialTools: 'employee/financial-tool',
  calculateStatePension: 'employee/calculate-state-pension',
  submitFeedback: 'employee/knowledgehub-video/feedback/',
  verifyPassword: 'employee/share/data',
  shareAccount: 'employee/share/switch',
  getPensionProviderInfo: 'employee/pension-provider/',
  checkAppVersion: 'checkAppVersion?',
  getMasterclasses: 'admin/events/',
  getMasterclassesDetail: 'admin/eventbrite/event/',
  getMasterclassesDescription: 'admin/eventbrite/event/description/',
  getOnboardingTile: 'employee/dashboard-onboarding-tile',
  updateOnboardingBadge: 'employee/dashboard-onboarding-tile',
  getFinancialPlannerDetail: 'employee/financial-planner-details',
  getSavedFinancialPlan: 'employee/financial-planner/',
  getFinancialSummary: 'employee/financial-summary',
  updateFinancialPlan: 'employee/financial-planner/',
  addFinancialPlan: 'employee/financial-planner/',
  subscriptionPlanDetail: 'employee/downgrade-request-details',
  getWealthAdvisors: 'employee/wealth-advisors/',
  deleteTransaction: 'employee/pension-accounts/transactions/',
  getYodleeAccounts: 'employee/yodlee/accounts/?',
  createPensionMultiple: 'employee/pension-accounts/private/multiple-create',
  drivers: 'drivers',
  lat_long: 'lat-long',
  customer_notification: 'customer-notification',



  getEmployerContributionData: (
    employeeId,
    employee_contribution,
    activation_date,
  ) =>
    `employee/${employeeId}/employer-contribution?employee_contribution=${employee_contribution}&activation_date=${activation_date}`,

  getSmartLightboxData: (userId, pension_account_id) =>
    `employee/smart-lightbox-data/${userId}/?pension_account_id=${pension_account_id}`,

  getNewEmployeeSavingRate: (userId, newSavingRate, pension_account_id) =>
    `employee/small-steps-data/${userId}/?new_employee_savings_rate=${newSavingRate}&pension_account_id=${pension_account_id}`,

  getLightboxTwoData: (userId, pension_account_id) =>
    `employee/light-box-2/${userId}/?pension_account_id=${pension_account_id}`,
};
